const choices = {
    activities:[
    "going shopping",
    "walking in the park",
    "seeing a movie",
    "going to a concert",
    "hitting up a bar",
    "a board game",
    "having a picnic",
    "an open mic",
    "an improv night",
    "karaoke",
    "paint and sip",
    "netflix and chill",
  ],
 restaurants: [
    "Chopsticks Inn",
    "Thai Bite",
    "Applebee's",
    "Ballast Point",
    "Stone Brewing",
    "Sushi Deli",
    "Filippi's Pizza Grotto",
    "Tofu House",
    "Tajima",
    "Dumpling Inn",
    "Taste of the Himalayas",
    "Board and Brew",
],

both: [
  "going shopping",
  "walking in the park",
  "seeing a movie",
  "going to a concert",
  "hitting up a bar",
  "a board game",
  "having a picnic",
  "an open mic",
  "an improv night",
  "karaoke",
  "paint and sip",
  "netflix and chill",
  "Chopsticks Inn",
  "Thai Bite",
  "Applebee's",
  "Ballast Point",
  "Stone Brewing",
  "Sushi Deli",
  "Filippi's Pizza Grotto",
  "Tofu House",
  "Tajima",
  "Dumpling Inn",
  "Taste of the Himalayas",
  "Board and Brew",
]
}
  export default choices